name: Scala CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build the stack
      run: docker-compose -f docker/docker-compose-local.yml up -d
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: run unit test
      run: sbt test
    - name: run database migration
      run: sbt "project market-db" "run update"
    - name: run integration test
      run: sbt it:test
